feat: replace manual frame counts with timer on musket
fishfolk/jumpy pull request #631
Opened 2023-02-17 04:15 UTC by lecoqjacob

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1r7e22oUdNv6HcakD3aoDthLGg6gDlkM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=pIi5lAe)

This was just a test to see the new time resource. I plan to go back and fix all other items post merge

2023-02-17 15:20 UTC, zicklag requested changes
Good idea!

Just got a couple small changes.

2023-02-17 15:20 UTC, zicklag commented on assets/elements/item/musket/musket.element.yaml
> +  cooldown_in_ms: 600
Could you update this to just be `cooldown` and then use [`humantime_serde`](https://docs.rs/humantime-serde/latest/humantime_serde/) to deserialize it to a duration?

That way we can specify the cooldown as `600ms`.

2023-02-17 15:20 UTC, zicklag commented on core/src/elements/musket.rs
> +        println!("musket ammo: {:?}", musket.cooldown);
Left over println.

2023-02-17 15:20 UTC, zicklag commented on core/src/session.rs
> +            .advance_exact(std::time::Duration::from_secs_f32(1.0 / crate::FPS));
Good catch!

2023-02-27 15:39 UTC, lecoqjacob commented
@zicklag updated to use the new serde method. I like it alot!

2023-02-27 16:39 UTC, zicklag approved these changes
Love it!

On a sidenote, I just realized today that moving _all_ of our timing related code to use timers like this could be important, because it would allow us to run at a lower frames frames-per-second update during network games if necessary without changing the physics speed.

So this is definitely something we want to do for everything.

bors merge

2023-02-27 16:41 UTC, zicklag commented
bors merge

2023-02-27 16:49 UTC, closed without merging