feat: sync sprite color and attachments.
fishfolk/jumpy pull request #738
Opened 2023-03-25 19:26 UTC by lecoqjacob

- If invincibility is active, have the player breathe slightly with their alpha

https://user-images.githubusercontent.com/9278174/227737396-c9e94623-1fb1-4872-a358-d47b1e078be7.mp4

2023-03-25 22:50 UTC, lecoqjacob commented
@zicklag should be good for a review now. I did some extra tidying with moving math utils and functions into a util module. I also created a globals module for us to store constants and static variables.

2023-03-25 22:50 UTC, lecoqjacob commented
The end result:

https://user-images.githubusercontent.com/9278174/227746006-23701a48-e765-4322-aec8-23abb37db690.mp4

2023-03-27 13:58 UTC, zicklag requested changes
One spelling fix, and otherwise it looks good!

2023-03-27 23:33 UTC, lecoqjacob commented
@zicklag ready

2023-03-27 23:47 UTC, zicklag approved these changes

2023-03-27 23:56 UTC, merged