fix: updated grenade.rs to use bones timer
fishfolk/jumpy pull request #740
Opened 2023-03-26 15:06 UTC by lvllvl

updated grenade.rs to use bones timer instead of manually setting time to 4.0 seconds

attempts to resolve #739

2023-03-27 13:49 UTC, zicklag requested changes

2023-03-27 13:49 UTC, zicklag commented on core/src/elements/grenade.rs
> +                            damage_delay: Timer::new(Duration::from_secs_f32(4.0), TimerMode::Once),
This `4.0` should come from the `fuse_time` out of the grenade meta.

2023-03-27 13:49 UTC, zicklag commented on core/src/elements/grenade.rs
> +        if grenade.damage_delay.elapsed_secs() >= *fuse_time {
Once we set the timer duratino from the `fuse_time`, we can just do this:

```suggestion
        if grenade.damage_delay.is_finished() {
```

2023-03-29 00:13 UTC, zicklag requested changes

2023-03-29 00:13 UTC, zicklag commented on core/src/elements/grenade.rs
> +    pub damage_delay: Timer,
Last change! Could you re-name this to `fuse_time`, and remove the comment, or update it with a new description.

2023-03-29 02:29 UTC, zicklag approved these changes
Looks good!

2023-03-29 02:33 UTC, merged

2023-03-29 02:35 UTC, lvllvl commented
> Looks good!

thanks for the help !